// Demo data for ManoSveikata (Lithuanian)

export const doctors = [
  {
    id: "d1",
    name: "Dr. Aistė Kazlauskienė",
    specialization: "Šeimos medicina",
    experience: 16,
    languages: ["Lietuvių", "Anglų", "Rusų"],
    price: 39,
    capacity: 25,
    activePatients: 14,
    rating: 4.9,
    reviews: 127,
    country: "Lietuva",
    available: true,
    remote: true,
    verified: true,
    nextAvailable: "2026-07-23",
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
    bio: "Šeimos gydytoja su 16 metų patirtimi, specializuojasi lėtinių ligų prevencijoje, kraujospūdžio valdyme ir paciento švietime. Tikinti, kad geras ryšys tarp gydytojo ir paciento – sveikatos pagrindas.",
    responseTime: "Per 24 val.",
    plans: [
      { name: "Standartinė priežiūra", price: 39, reviews: 1, video: 0 },
      { name: "Aktyvi priežiūra", price: 79, reviews: 2, video: 1 },
    ],
  },
  {
    id: "d2",
    name: "Dr. Mindaugas Vaitkus",
    specialization: "Kardiologija",
    experience: 22,
    languages: ["Lietuvių", "Anglų"],
    price: 59,
    capacity: 20,
    activePatients: 12,
    rating: 4.8,
    reviews: 89,
    country: "Lietuva",
    available: true,
    remote: true,
    verified: true,
    nextAvailable: "2026-07-24",
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop",
    bio: "Kardiologas, orientuotas į aukšto kraujospūdžio, aritmijų ir širdies prevencijos valdymą. Dirba su nuotolinio stebėjimo įranga.",
    responseTime: "Per 12 val.",
    plans: [{ name: "Kardiologinė priežiūra", price: 59, reviews: 1, video: 1 }],
  },
  {
    id: "d3",
    name: "Dr. Eglė Petrauskienė",
    specialization: "Endokrinologija",
    experience: 14,
    languages: ["Lietuvių", "Anglų", "Vokiečių"],
    price: 49,
    capacity: 22,
    activePatients: 18,
    rating: 4.9,
    reviews: 156,
    country: "Lietuva",
    available: true,
    remote: true,
    verified: true,
    nextAvailable: "2026-07-22",
    photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop",
    bio: "Endokrinologija – cukrinis diabetas, skydliaukės ligos, medžiagų apykaitos sutrikimai. Orientuota į paciento edukaciją.",
    responseTime: "Per 24 val.",
    plans: [{ name: "Endokrininė priežiūra", price: 49, reviews: 1, video: 0 }],
  },
  {
    id: "d4",
    name: "Dr. Tomas Žukauskas",
    specialization: "Vidaus ligos",
    experience: 19,
    languages: ["Lietuvių", "Anglų", "Lenkų"],
    price: 45,
    capacity: 30,
    activePatients: 20,
    rating: 4.7,
    reviews: 203,
    country: "Lietuva",
    available: false,
    remote: true,
    verified: true,
    nextAvailable: "2026-08-01",
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop",
    bio: "Vidaus ligų gydytojas su plačiu profilaktikos ir diagnostikos patirties spektru.",
    responseTime: "Per 48 val.",
    plans: [{ name: "Vidaus ligų priežiūra", price: 45, reviews: 1, video: 0 }],
  },
  {
    id: "d5",
    name: "Dr. Rūta Stankevičienė",
    specialization: "Profilaktinė medicina",
    experience: 12,
    languages: ["Lietuvių", "Anglų"],
    price: 35,
    capacity: 28,
    activePatients: 10,
    rating: 4.8,
    reviews: 74,
    country: "Lietuva",
    available: true,
    remote: true,
    verified: true,
    nextAvailable: "2026-07-21",
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
    bio: "Profilaktinės medicinos specialistė. Padeda pacientams užkirsti kelią ligoms prieš jos atsirandant.",
    responseTime: "Per 24 val.",
    plans: [{ name: "Profilaktinė priežiūra", price: 35, reviews: 1, video: 0 }],
  },
  {
    id: "d6",
    name: "Dr. Andrius Balčiūnas",
    specialization: "Gyvensenos medicina",
    experience: 10,
    languages: ["Lietuvių", "Anglų", "Norvegų"],
    price: 39,
    capacity: 25,
    activePatients: 8,
    rating: 4.9,
    reviews: 62,
    country: "Lietuva",
    available: true,
    remote: true,
    verified: true,
    nextAvailable: "2026-07-25",
    photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop",
    bio: "Gyvensenos medicinos gydytojas – mityba, fizinis aktyvumas, miego higiena, streso valdymas.",
    responseTime: "Per 24 val.",
    plans: [{ name: "Gyvensenos priežiūra", price: 39, reviews: 1, video: 1 }],
  },
  {
    id: "d7",
    name: "Dr. Lina Jankauskienė",
    specialization: "Šeimos medicina",
    experience: 18,
    languages: ["Lietuvių", "Anglų"],
    price: 42,
    capacity: 24,
    activePatients: 16,
    rating: 4.7,
    reviews: 98,
    country: "Lietuva",
    available: true,
    remote: false,
    verified: true,
    nextAvailable: "2026-07-28",
    photo: "https://images.unsplash.com/photo-1559239115-eea44a4c85d3?w=400&h=400&fit=crop",
    bio: "Šeimos gydytoja, dirbanti su šeimomis ir lėtiniais pacientais. Ypatingas dėmesys senjorams.",
    responseTime: "Per 48 val.",
    plans: [{ name: "Šeimos priežiūra", price: 42, reviews: 1, video: 0 }],
  },
  {
    id: "d8",
    name: "Dr. Paulius Norkus",
    specialization: "Kardiologija",
    experience: 25,
    languages: ["Lietuvių", "Anglų", "Prancūzų"],
    price: 69,
    capacity: 15,
    activePatients: 13,
    rating: 5.0,
    reviews: 141,
    country: "Lietuva",
    available: false,
    remote: true,
    verified: true,
    nextAvailable: "2026-08-05",
    photo: "https://images.unsplash.com/photo-1582769218028-0b6b9b8d9a8c?w=400&h=400&fit=crop",
    bio: "Vyriausias kardiologas komandoje. Aukšto lygio profilaktika ir sudėtingų atvejų valdymas.",
    responseTime: "Per 12 val.",
    plans: [{ name: "Premium kardiologija", price: 69, reviews: 2, video: 2 }],
  },
];

// Generate 30 days of blood pressure readings for Jonas
export function generateBloodPressureData() {
  const readings = [];
  const today = new Date("2026-07-21");
  for (let i = 29; i >= 0; i--) {
    const date = new Date(today);
    date.setDate(date.getDate() - i);
    const morning = {
      date: date.toISOString().split("T")[0],
      time: "07:30",
      systolic: 128 + Math.round(Math.sin(i / 3) * 6 + Math.random() * 8),
      diastolic: 82 + Math.round(Math.sin(i / 3) * 4 + Math.random() * 5),
      pulse: 68 + Math.round(Math.random() * 8),
      source: i % 3 === 0 ? "Rankinis įvedimas" : "OMRON",
      position: "Sėdint",
      notes: i === 5 ? "Po mankštos" : "",
    };
    const evening = {
      date: date.toISOString().split("T")[0],
      time: "19:45",
      systolic: 134 + Math.round(Math.sin(i / 2) * 5 + Math.random() * 7),
      diastolic: 86 + Math.round(Math.sin(i / 2) * 3 + Math.random() * 4),
      pulse: 72 + Math.round(Math.random() * 7),
      source: "OMRON",
      position: "Sėdint",
      notes: "",
    };
    readings.push(morning, evening);
  }
  return readings;
}

export const bloodPressureData = generateBloodPressureData();

export const labResults = [
  { marker: "Bendrasis cholesterolis", value: 5.8, unit: "mmol/L", refLow: 3.0, refHigh: 5.0, date: "2026-07-15", status: "above", trend: "up" },
  { marker: "MTL cholesterolis", value: 3.9, unit: "mmol/L", refLow: 0, refHigh: 3.0, date: "2026-07-15", status: "above", trend: "up" },
  { marker: "DTL cholesterolis", value: 1.2, unit: "mmol/L", refLow: 1.0, refHigh: 2.0, date: "2026-07-15", status: "within", trend: "stable" },
  { marker: "Trigliceridai", value: 1.5, unit: "mmol/L", refLow: 0, refHigh: 1.7, date: "2026-07-15", status: "within", trend: "down" },
  { marker: "Gliukozė", value: 5.6, unit: "mmol/L", refLow: 3.9, refHigh: 6.1, date: "2026-07-15", status: "within", trend: "stable" },
  { marker: "HbA1c", value: 5.4, unit: "%", refLow: 4.0, refHigh: 5.7, date: "2026-07-15", status: "within", trend: "down" },
  { marker: "Kreatininas", value: 84, unit: "µmol/L", refLow: 60, refHigh: 110, date: "2026-07-15", status: "within", trend: "stable" },
  { marker: "ALT", value: 32, unit: "U/L", refLow: 0, refHigh: 41, date: "2026-07-15", status: "within", trend: "stable" },
  { marker: "AST", value: 28, unit: "U/L", refLow: 0, refHigh: 40, date: "2026-07-15", status: "within", trend: "stable" },
  { marker: "Vitaminas D", value: 28, unit: "ng/mL", refLow: 30, refHigh: 100, date: "2026-07-15", status: "below", trend: "down" },
  { marker: "Ferritinas", value: 65, unit: "µg/L", refLow: 30, refHigh: 400, date: "2026-07-15", status: "within", trend: "stable" },
  { marker: "Hemoglobinas", value: 142, unit: "g/L", refLow: 130, refHigh: 170, date: "2026-07-15", status: "within", trend: "stable" },
];

export const medications = [
  {
    id: "m1",
    name: "Lisinoprilis",
    dose: "10 mg",
    frequency: "1 kartą per dieną, ryte",
    startDate: "2026-03-01",
    doctor: "Dr. Aistė Kazlauskienė",
    instructions: "Gerti ryte prieš valgį, gausiai užsigeriant vandeniu.",
    active: true,
    reminder: "07:00",
    takenToday: true,
  },
  {
    id: "m2",
    name: "Atorvastatinas",
    dose: "20 mg",
    frequency: "1 kartą per dieną, vakare",
    startDate: "2026-03-01",
    doctor: "Dr. Aistė Kazlauskienė",
    instructions: "Vakare, geriausia prieš miegą.",
    active: true,
    reminder: "21:00",
    takenToday: false,
  },
];

export const aiSummaries = [
  {
    id: "s1",
    period: "Savaitė 2026-07-14 – 2026-07-20",
    type: "weekly",
    sections: [
      { title: "Pagrindiniai pokyčiai", content: "Vidutinis sistolinis kraujospūdis pakilo 3 mmHg (132 → 135). Vidutinis diastolinis išliko stabilus (85)." },
      { title: "Kraujospūdžio tendencija", content: "Vakariniai matavimai rodo didesnes reikšmes nei rytiniai (vid. 135/87 vakare vs 129/82 ryte)." },
      { title: "Laboratoriniai pokyčiai", content: "Bendrasis cholesterolis viršijo normą (5.8 mmol/L). Vitaminas D žemiau normos (28 ng/mL)." },
      { title: "Simptomai", content: "Pacientas pranešė apie lengvą nuovargį trečiadienį." },
      { title: "Vaistų vartojimas", content: "Lisinoprilis vartojamas reguliariai. Atorvastatino praleista viena dozė (penktadienis)." },
      { title: "Trūkstami duomenys", content: "Nėra svorio matavimų per pastarąją savaitę. Fizinio aktyvumo duomenys nepilni." },
      { title: "Gydytojo peržiūrai", content: "Kraujospūdžio kilimo tendencija. Cholesterolis virš normos. Vertinamas vaistų veiksmingumas." },
      { title: "Klausimai kitai konsultacijai", content: "Ar reikia koreguoti Atorvastatino dozę? Ar vertėtų pradėti vartoti vitaminą D?" },
    ],
  },
  {
    id: "s2",
    period: "Mėnuo 2026-06-21 – 2026-07-20",
    type: "monthly",
    sections: [
      { title: "Pagrindiniai pokyčiai", content: "Per mėnesį kraujospūdis išlaikė vidutinį lygį su lengva kilimo tendencija. Cholesterolis viršijo normą." },
      { title: "Kraujospūdžio tendencija", content: "Mėnesio vidurkis: 132/84. Aukščiausias matavimas: 142/91 (liepos 12 d.)." },
      { title: "Laboratoriniai pokyčiai", content: "Nauji rezultatai rodo padidėjusį cholesterolį ir mažą vitaminą D." },
      { title: "Vaistų vartojimas", content: "Atorvastatinas praleistas 3 kartus per mėnesį. Lisinoprilis vartotas reguliariai." },
      { title: "Trūkstami duomenys", content: "Trūksta svorio ir fizinio aktyvumo duomenų." },
      { title: "Gydytojo peržiūrai", content: "Rekomenduojama peržiūrėti cholesterolio gydymą. Svarstyti vitamino D papildymą." },
      { title: "Klausimai konsultacijai", content: "Ar reikia didinti Atorvastatino dozę? Ar verta atlikti pakartotinę lipidogramą?" },
    ],
  },
];

export const alerts = [
  {
    id: "a1",
    level: "urgent",
    title: "Aukštas kraujospūdis",
    message: "Paskutinio matavimo sistolinis kraujospūdis viršijo nustatytą ribą (140 mmHg). Reikšmė: 142/91.",
    date: "2026-07-20",
    source: "OMRON",
  },
  {
    id: "a2",
    level: "review",
    title: "Cholesterolis virš normos",
    message: "Naujausi laboratoriniai rezultatai rodo padidėjusį bendrąjį cholesterolį (5.8 mmol/L).",
    date: "2026-07-15",
    source: "Laboratorija",
  },
  {
    id: "a3",
    level: "priority",
    title: "Praleista vaistų dozė",
    message: "Atorvastatino dozė praleista liepos 19 d. (penktadienis).",
    date: "2026-07-19",
    source: "Vaistų priminimas",
  },
  {
    id: "a4",
    level: "info",
    title: "Vitaminas D žemiau normos",
    message: "Vitamino D lygis 28 ng/mL – žemiau rekomenduojamos normos (30–100).",
    date: "2026-07-15",
    source: "Laboratorija",
  },
];

export const messages = [
  { id: "msg1", from: "doctor", text: "Sveiki, Jonai. Peržiūrėjau Jūsų mėnesio santrauką. Cholesterolis šiek tiek padidėjęs – aptarsime tai artimiausios konsultacijos metu.", time: "2026-07-19 14:30" },
  { id: "msg2", from: "patient", text: "Ačiū, gydytoja. Ar reikės ką nors keisti vaistuose?", time: "2026-07-19 15:10" },
  { id: "msg3", from: "doctor", text: "Kol kas paliksime dabartinę dozę. Po mėnesio pakartosime lipidogramą. Nepamirškite vakarinio Atorvastatino.", time: "2026-07-19 15:45" },
  { id: "msg4", from: "patient", text: "Supratau, ačiū už patarimą.", time: "2026-07-19 16:00" },
];

export const healthTimeline = [
  { id: "t1", icon: "heart", title: "Kraujospūdžio matavimas importuotas", desc: "142/91 mmHg iš OMRON įrenginio", date: "2026-07-20 19:45", type: "bp" },
  { id: "t2", icon: "alert", title: "Aktyvus įspėjimas", desc: "Aukštas kraujospūdis viršijo nustatytą ribą", date: "2026-07-20 19:46", type: "alert" },
  { id: "t3", icon: "file", title: "AI santrauka sugeneruota", desc: "Savaitės sveikatos santrauka paruošta", date: "2026-07-20 08:00", type: "summary" },
  { id: "t4", icon: "stethoscope", title: "Gydytojo peržiūra", desc: "Dr. Aistė Kazlauskienė peržiūrėjo mėnesio ataskaitą", date: "2026-07-19 14:00", type: "review" },
  { id: "t5", icon: "flask", title: "Laboratoriniai rezultatai įkelti", desc: "Lipidograma ir biochemija", date: "2026-07-15 10:30", type: "lab" },
  { id: "t6", icon: "pill", title: "Vaistų priminimas įvykdytas", desc: "Lisinoprilis 10 mg – pažymėta kaip išgerta", date: "2026-07-15 07:05", type: "medication" },
];

export const integrations = [
  { name: "OMRON kraujospūdžio monitoriai", status: "connected", desc: "Kraujospūdžio stebėjimas", icon: "heart" },
  { name: "Apple Health", status: "available", desc: "Sveikatos duomenys iš iPhone", icon: "apple" },
  { name: "Android Health Connect", status: "available", desc: "Sveikatos duomenys iš Android", icon: "phone" },
  { name: "Garmin", status: "coming-soon", desc: "Fizinio aktyvumo stebėjimas", icon: "watch" },
  { name: "Fitbit", status: "coming-soon", desc: "Aktyvumo ir miego stebėjimas", icon: "watch" },
  { name: "Oura", status: "coming-soon", desc: "Miego ir sveikatos žiedas", icon: "watch" },
  { name: "Laboratoriniai rezultatai", status: "available", desc: "PDF ataskaitų įkėlimas", icon: "flask" },
  { name: "Medicininiai PDF dokumentai", status: "available", desc: "Ataskaitų ir išrašų saugojimas", icon: "file" },
  { name: "Rankiniai matavimai", status: "connected", desc: "Rankinis duomenų įvedimas", icon: "edit" },
];

export const patientProfile = {
  name: "Jonas Petrauskas",
  age: 58,
  gender: "Vyras",
  height: 178,
  weight: 86,
  bmi: 27.1,
  bloodType: "A+",
  phone: "+370 600 12345",
  email: "jonas.petrauskas@email.lt",
  city: "Vilnius",
  emergencyContact: "Ona Petrauskienė (+370 699 87654)",
  allergies: ["Penicilinas"],
  diagnoses: ["Arterinė hipertenzija (I10)", "Hipercholesterolemija"],
  surgeries: ["Tonzilių pašalinimas (1985)"],
  familyHistory: "Tėvas – miokardo infarktas (65 m.)",
  smoking: "Nerūko",
  alcohol: "Retai",
  activity: "Vidutinis (2–3 kartus/sav.)",
  sleep: "6–7 val.",
  selectedDoctor: "Dr. Aistė Kazlauskienė",
  plan: "Gydytojo priežiūra – €39/mėn",
  nextReview: "2026-08-19",
};

export const doctorPatients = [
  { id: "p1", name: "Jonas Petrauskas", age: 58, condition: "Arterinė hipertenzija", status: "Reikia dėmesio", bp: "142/91", lastReview: "2026-06-19", nextReview: "2026-08-19", alert: "urgent", plan: "€39/mėn" },
  { id: "p2", name: "Marytė Žilinskaitė", age: 64, condition: "2 tipo cukrinis diabetas", status: "Stabilus", bp: "128/82", lastReview: "2026-07-05", nextReview: "2026-08-05", alert: "none", plan: "€39/mėn" },
  { id: "p3", name: "Petras Kazlauskas", age: 71, condition: "Koronarinė širdies liga", status: "Reikia peržiūros", bp: "138/88", lastReview: "2026-06-20", nextReview: "2026-07-20", alert: "review", plan: "€79/mėn" },
  { id: "p4", name: "Ona Vasiliauskienė", age: 55, condition: "Hipercholesterolemija", status: "Stabilus", bp: "124/80", lastReview: "2026-07-01", nextReview: "2026-08-01", alert: "none", plan: "€39/mėn" },
  { id: "p5", name: "Vytautas Petrauskas", age: 62, condition: "Arterinė hipertenzija", status: "Reikia dėmesio", bp: "146/93", lastReview: "2026-06-28", nextReview: "2026-07-28", alert: "priority", plan: "€79/mėn" },
  { id: "p6", name: "Danguolė Balčiūnienė", age: 49, condition: "Skydliaukės hipotireozė", status: "Stabilus", bp: "118/76", lastReview: "2026-07-03", nextReview: "2026-08-03", alert: "none", plan: "€39/mėn" },
  { id: "p7", name: "Algirdas Stankevičius", age: 67, condition: "2 tipo cukrinis diabetas", status: "Reikia peržiūros", bp: "134/86", lastReview: "2026-06-15", nextReview: "2026-07-15", alert: "review", plan: "€79/mėn" },
  { id: "p8", name: "Nijolė Jankauskienė", age: 60, condition: "Arterinė hipertenzija", status: "Stabilus", bp: "126/81", lastReview: "2026-07-08", nextReview: "2026-08-08", alert: "none", plan: "€39/mėn" },
  { id: "p9", name: "Bronius Vaitkus", age: 73, condition: "Koronarinė širdies liga", status: "Reikia dėmesio", bp: "144/92", lastReview: "2026-06-22", nextReview: "2026-07-22", alert: "urgent", plan: "€79/mėn" },
  { id: "p10", name: "Staselė Kazlauskienė", age: 56, condition: "Hipercholesterolemija", status: "Stabilus", bp: "130/83", lastReview: "2026-07-10", nextReview: "2026-08-10", alert: "none", plan: "€39/mėn" },
  { id: "p11", name: "Eugenijus Petrauskas", age: 45, condition: "Profilaktinė priežiūra", status: "Stabilus", bp: "120/78", lastReview: "2026-07-12", nextReview: "2026-08-12", alert: "none", plan: "€39/mėn" },
  { id: "p12", name: "Irena Vasiliauskienė", age: 52, condition: "Miego sutrikimai", status: "Reikia peržiūros", bp: "132/85", lastReview: "2026-06-25", nextReview: "2026-07-25", alert: "review", plan: "€39/mėn" },
  { id: "p13", name: "Gintaras Žukauskas", age: 59, condition: "Arterinė hipertenzija", status: "Stabilus", bp: "128/82", lastReview: "2026-07-06", nextReview: "2026-08-06", alert: "none", plan: "€39/mėn" },
  { id: "p14", name: "Aldona Petrauskienė", age: 66, condition: "2 tipo cukrinis diabetas", status: "Stabilus", bp: "130/84", lastReview: "2026-07-02", nextReview: "2026-08-02", alert: "none", plan: "€39/mėn" },
];