// Demo data for MyHealthPilot (English)

export const doctors = [
  {
    id: "d1",
    name: "Dr. Aistė Kazlauskienė",
    specialization: "Family Medicine",
    experience: 16,
    languages: ["Lithuanian", "English", "Russian"],
    price: 39,
    capacity: 25,
    activePatients: 14,
    rating: 4.9,
    reviews: 127,
    country: "Lithuania",
    available: true,
    remote: true,
    verified: true,
    nextAvailable: "2026-07-23",
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
    bio: "Family doctor with 16 years of experience, specializing in chronic disease prevention, blood pressure management, and patient education. Believes a strong doctor-patient relationship is the foundation of health.",
    responseTime: "Within 24 hours",
    plans: [
      { name: "Standard Care", price: 39, reviews: 1, video: 0 },
      { name: "Active Care", price: 79, reviews: 2, video: 1 },
    ],
  },
  {
    id: "d2",
    name: "Dr. Mindaugas Vaitkus",
    specialization: "Cardiology",
    experience: 22,
    languages: ["Lithuanian", "English"],
    price: 59,
    capacity: 20,
    activePatients: 12,
    rating: 4.8,
    reviews: 89,
    country: "Lithuania",
    available: true,
    remote: true,
    verified: true,
    nextAvailable: "2026-07-24",
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop",
    bio: "Cardiologist focused on managing high blood pressure, arrhythmias, and heart disease prevention. Works with remote monitoring equipment.",
    responseTime: "Within 12 hours",
    plans: [{ name: "Cardiology Care", price: 59, reviews: 1, video: 1 }],
  },
  {
    id: "d3",
    name: "Dr. Eglė Petrauskienė",
    specialization: "Endocrinology",
    experience: 14,
    languages: ["Lithuanian", "English", "German"],
    price: 49,
    capacity: 22,
    activePatients: 18,
    rating: 4.9,
    reviews: 156,
    country: "Lithuania",
    available: true,
    remote: true,
    verified: true,
    nextAvailable: "2026-07-22",
    photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop",
    bio: "Endocrinology – diabetes, thyroid disorders, metabolic conditions. Focused on patient education.",
    responseTime: "Within 24 hours",
    plans: [{ name: "Endocrinology Care", price: 49, reviews: 1, video: 0 }],
  },
  {
    id: "d4",
    name: "Dr. Tomas Žukauskas",
    specialization: "Internal Medicine",
    experience: 19,
    languages: ["Lithuanian", "English", "Polish"],
    price: 45,
    capacity: 30,
    activePatients: 20,
    rating: 4.7,
    reviews: 203,
    country: "Lithuania",
    available: false,
    remote: true,
    verified: true,
    nextAvailable: "2026-08-01",
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop",
    bio: "Internal medicine doctor with broad experience in prevention and diagnostics.",
    responseTime: "Within 48 hours",
    plans: [{ name: "Internal Medicine Care", price: 45, reviews: 1, video: 0 }],
  },
  {
    id: "d5",
    name: "Dr. Rūta Stankevičienė",
    specialization: "Preventive Medicine",
    experience: 12,
    languages: ["Lithuanian", "English"],
    price: 35,
    capacity: 28,
    activePatients: 10,
    rating: 4.8,
    reviews: 74,
    country: "Lithuania",
    available: true,
    remote: true,
    verified: true,
    nextAvailable: "2026-07-21",
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
    bio: "Preventive medicine specialist. Helps patients prevent diseases before they arise.",
    responseTime: "Within 24 hours",
    plans: [{ name: "Preventive Care", price: 35, reviews: 1, video: 0 }],
  },
  {
    id: "d6",
    name: "Dr. Andrius Balčiūnas",
    specialization: "Lifestyle Medicine",
    experience: 10,
    languages: ["Lithuanian", "English", "Norwegian"],
    price: 39,
    capacity: 25,
    activePatients: 8,
    rating: 4.9,
    reviews: 62,
    country: "Lithuania",
    available: true,
    remote: true,
    verified: true,
    nextAvailable: "2026-07-25",
    photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop",
    bio: "Lifestyle medicine doctor – nutrition, physical activity, sleep hygiene, stress management.",
    responseTime: "Within 24 hours",
    plans: [{ name: "Lifestyle Care", price: 39, reviews: 1, video: 1 }],
  },
  {
    id: "d7",
    name: "Dr. Lina Jankauskienė",
    specialization: "Family Medicine",
    experience: 18,
    languages: ["Lithuanian", "English"],
    price: 42,
    capacity: 24,
    activePatients: 16,
    rating: 4.7,
    reviews: 98,
    country: "Lithuania",
    available: true,
    remote: false,
    verified: true,
    nextAvailable: "2026-07-28",
    photo: "https://images.unsplash.com/photo-1559239115-eea44a4c85d3?w=400&h=400&fit=crop",
    bio: "Family doctor working with families and chronic patients. Special attention to seniors.",
    responseTime: "Within 48 hours",
    plans: [{ name: "Family Care", price: 42, reviews: 1, video: 0 }],
  },
  {
    id: "d8",
    name: "Dr. Paulius Norkus",
    specialization: "Cardiology",
    experience: 25,
    languages: ["Lithuanian", "English", "French"],
    price: 69,
    capacity: 15,
    activePatients: 13,
    rating: 5.0,
    reviews: 141,
    country: "Lithuania",
    available: false,
    remote: true,
    verified: true,
    nextAvailable: "2026-08-05",
    photo: "https://images.unsplash.com/photo-1582769218028-0b6b9b8d9a8c?w=400&h=400&fit=crop",
    bio: "Senior cardiologist on the team. High-level prevention and complex case management.",
    responseTime: "Within 12 hours",
    plans: [{ name: "Premium Cardiology", price: 69, reviews: 2, video: 2 }],
  },
];

export function generateBloodPressureData() {
  const readings = [];
  const today = new Date("2026-07-21");
  for (let i = 29; i >= 0; i--) {
    const date = new Date(today);
    date.setDate(date.getDate() - i);
    const morning = {
      date: date.toISOString().split("T")[0],
      time: "07:30",
      systolic: 128 + Math.round(Math.sin(i / 3) * 6 + Math.random() * 8),
      diastolic: 82 + Math.round(Math.sin(i / 3) * 4 + Math.random() * 5),
      pulse: 68 + Math.round(Math.random() * 8),
      source: i % 3 === 0 ? "Manual entry" : "OMRON",
      position: "Sitting",
      notes: i === 5 ? "After exercise" : "",
    };
    const evening = {
      date: date.toISOString().split("T")[0],
      time: "19:45",
      systolic: 134 + Math.round(Math.sin(i / 2) * 5 + Math.random() * 7),
      diastolic: 86 + Math.round(Math.sin(i / 2) * 3 + Math.random() * 4),
      pulse: 72 + Math.round(Math.random() * 7),
      source: "OMRON",
      position: "Sitting",
      notes: "",
    };
    readings.push(morning, evening);
  }
  return readings;
}

export const bloodPressureData = generateBloodPressureData();

export const labResults = [
  { marker: "Total cholesterol", value: 5.8, unit: "mmol/L", refLow: 3.0, refHigh: 5.0, date: "2026-07-15", status: "above", trend: "up" },
  { marker: "LDL cholesterol", value: 3.9, unit: "mmol/L", refLow: 0, refHigh: 3.0, date: "2026-07-15", status: "above", trend: "up" },
  { marker: "HDL cholesterol", value: 1.2, unit: "mmol/L", refLow: 1.0, refHigh: 2.0, date: "2026-07-15", status: "within", trend: "stable" },
  { marker: "Triglycerides", value: 1.5, unit: "mmol/L", refLow: 0, refHigh: 1.7, date: "2026-07-15", status: "within", trend: "down" },
  { marker: "Glucose", value: 5.6, unit: "mmol/L", refLow: 3.9, refHigh: 6.1, date: "2026-07-15", status: "within", trend: "stable" },
  { marker: "HbA1c", value: 5.4, unit: "%", refLow: 4.0, refHigh: 5.7, date: "2026-07-15", status: "within", trend: "down" },
  { marker: "Creatinine", value: 84, unit: "µmol/L", refLow: 60, refHigh: 110, date: "2026-07-15", status: "within", trend: "stable" },
  { marker: "ALT", value: 32, unit: "U/L", refLow: 0, refHigh: 41, date: "2026-07-15", status: "within", trend: "stable" },
  { marker: "AST", value: 28, unit: "U/L", refLow: 0, refHigh: 40, date: "2026-07-15", status: "within", trend: "stable" },
  { marker: "Vitamin D", value: 28, unit: "ng/mL", refLow: 30, refHigh: 100, date: "2026-07-15", status: "below", trend: "down" },
  { marker: "Ferritin", value: 65, unit: "µg/L", refLow: 30, refHigh: 400, date: "2026-07-15", status: "within", trend: "stable" },
  { marker: "Hemoglobin", value: 142, unit: "g/L", refLow: 130, refHigh: 170, date: "2026-07-15", status: "within", trend: "stable" },
];

export const medications = [
  {
    id: "m1",
    name: "Lisinopril",
    dose: "10 mg",
    frequency: "Once daily, morning",
    startDate: "2026-03-01",
    doctor: "Dr. Aistė Kazlauskienė",
    instructions: "Take in the morning before meals, with plenty of water.",
    active: true,
    reminder: "07:00",
    takenToday: true,
  },
  {
    id: "m2",
    name: "Atorvastatin",
    dose: "20 mg",
    frequency: "Once daily, evening",
    startDate: "2026-03-01",
    doctor: "Dr. Aistė Kazlauskienė",
    instructions: "In the evening, preferably before bed.",
    active: true,
    reminder: "21:00",
    takenToday: false,
  },
];

export const aiSummaries = [
  {
    id: "s1",
    period: "Week 2026-07-14 – 2026-07-20",
    type: "weekly",
    sections: [
      { title: "Key changes", content: "Average systolic blood pressure rose 3 mmHg (132 → 135). Average diastolic remained stable (85)." },
      { title: "Blood pressure trend", content: "Evening measurements show higher values than morning (avg 135/87 evening vs 129/82 morning)." },
      { title: "Lab changes", content: "Total cholesterol exceeded the normal range (5.8 mmol/L). Vitamin D below normal (28 ng/mL)." },
      { title: "Symptoms", content: "Patient reported mild fatigue on Wednesday." },
      { title: "Medication adherence", content: "Lisinopril taken regularly. One Atorvastatin dose missed (Friday)." },
      { title: "Missing data", content: "No weight measurements in the past week. Physical activity data incomplete." },
      { title: "For doctor's review", content: "Blood pressure upward trend. Cholesterol above range. Medication effectiveness to be assessed." },
      { title: "Questions for next consultation", content: "Should the Atorvastatin dose be adjusted? Should vitamin D supplementation be started?" },
    ],
  },
  {
    id: "s2",
    period: "Month 2026-06-21 – 2026-07-20",
    type: "monthly",
    sections: [
      { title: "Key changes", content: "Over the month, blood pressure maintained an average level with a slight upward trend. Cholesterol exceeded the normal range." },
      { title: "Blood pressure trend", content: "Monthly average: 132/84. Highest reading: 142/91 (July 12)." },
      { title: "Lab changes", content: "New results show elevated cholesterol and low vitamin D." },
      { title: "Medication adherence", content: "Atorvastatin missed 3 times this month. Lisinopril taken regularly." },
      { title: "Missing data", content: "Weight and physical activity data are missing." },
      { title: "For doctor's review", content: "Recommended to review cholesterol treatment. Consider vitamin D supplementation." },
      { title: "Questions for consultation", content: "Should the Atorvastatin dose be increased? Should a repeat lipid panel be done?" },
    ],
  },
];

export const alerts = [
  {
    id: "a1",
    level: "urgent",
    title: "High blood pressure",
    message: "The latest systolic blood pressure reading exceeded the set limit (140 mmHg). Value: 142/91.",
    date: "2026-07-20",
    source: "OMRON",
  },
  {
    id: "a2",
    level: "review",
    title: "Cholesterol above range",
    message: "Recent lab results show elevated total cholesterol (5.8 mmol/L).",
    date: "2026-07-15",
    source: "Laboratory",
  },
  {
    id: "a3",
    level: "priority",
    title: "Missed medication dose",
    message: "Atorvastatin dose was missed on July 19 (Friday).",
    date: "2026-07-19",
    source: "Medication reminder",
  },
  {
    id: "a4",
    level: "info",
    title: "Vitamin D below range",
    message: "Vitamin D level is 28 ng/mL – below the recommended range (30–100).",
    date: "2026-07-15",
    source: "Laboratory",
  },
];

export const messages = [
  { id: "msg1", from: "doctor", text: "Hello, Jonas. I've reviewed your monthly summary. Your cholesterol is slightly elevated – we'll discuss this at your next consultation.", time: "2026-07-19 14:30" },
  { id: "msg2", from: "patient", text: "Thank you, doctor. Will any medications need to be changed?", time: "2026-07-19 15:10" },
  { id: "msg3", from: "doctor", text: "We'll keep the current dose for now. We'll repeat the lipid panel in a month. Don't forget your evening Atorvastatin.", time: "2026-07-19 15:45" },
  { id: "msg4", from: "patient", text: "Understood, thanks for the advice.", time: "2026-07-19 16:00" },
];

export const healthTimeline = [
  { id: "t1", icon: "heart", title: "Blood pressure measurement imported", desc: "142/91 mmHg from OMRON device", date: "2026-07-20 19:45", type: "bp" },
  { id: "t2", icon: "alert", title: "Active alert", desc: "High blood pressure exceeded set limit", date: "2026-07-20 19:46", type: "alert" },
  { id: "t3", icon: "file", title: "AI summary generated", desc: "Weekly health summary ready", date: "2026-07-20 08:00", type: "summary" },
  { id: "t4", icon: "stethoscope", title: "Doctor review", desc: "Dr. Aistė Kazlauskienė reviewed the monthly report", date: "2026-07-19 14:00", type: "review" },
  { id: "t5", icon: "flask", title: "Lab results uploaded", desc: "Lipid panel and biochemistry", date: "2026-07-15 10:30", type: "lab" },
  { id: "t6", icon: "pill", title: "Medication reminder completed", desc: "Lisinopril 10 mg – marked as taken", date: "2026-07-15 07:05", type: "medication" },
];

export const integrations = [
  { name: "OMRON blood pressure monitors", status: "connected", desc: "Blood pressure monitoring", icon: "heart" },
  { name: "Apple Health", status: "available", desc: "Health data from iPhone", icon: "apple" },
  { name: "Android Health Connect", status: "available", desc: "Health data from Android", icon: "phone" },
  { name: "Garmin", status: "coming-soon", desc: "Physical activity tracking", icon: "watch" },
  { name: "Fitbit", status: "coming-soon", desc: "Activity and sleep tracking", icon: "watch" },
  { name: "Oura", status: "coming-soon", desc: "Sleep and health ring", icon: "watch" },
  { name: "Lab results", status: "available", desc: "PDF report upload", icon: "flask" },
  { name: "Medical PDF documents", status: "available", desc: "Report and record storage", icon: "file" },
  { name: "Manual measurements", status: "connected", desc: "Manual data entry", icon: "edit" },
];

export const patientProfile = {
  name: "Jonas Petrauskas",
  age: 58,
  gender: "Male",
  height: 178,
  weight: 86,
  bmi: 27.1,
  bloodType: "A+",
  phone: "+370 600 12345",
  email: "jonas.petrauskas@email.lt",
  city: "Vilnius",
  emergencyContact: "Ona Petrauskienė (+370 699 87654)",
  allergies: ["Penicillin"],
  diagnoses: ["Arterial hypertension (I10)", "Hypercholesterolemia"],
  surgeries: ["Tonsillectomy (1985)"],
  familyHistory: "Father – myocardial infarction (age 65)",
  smoking: "Non-smoker",
  alcohol: "Rarely",
  activity: "Moderate (2–3 times/week)",
  sleep: "6–7 hours",
  selectedDoctor: "Dr. Aistė Kazlauskienė",
  plan: "Doctor's Care – €39/mo",
  nextReview: "2026-08-19",
};

export const doctorPatients = [
  { id: "p1", name: "Jonas Petrauskas", age: 58, condition: "Arterial hypertension", status: "Needs attention", bp: "142/91", lastReview: "2026-06-19", nextReview: "2026-08-19", alert: "urgent", plan: "€39/mo" },
  { id: "p2", name: "Marytė Žilinskaitė", age: 64, condition: "Type 2 diabetes", status: "Stable", bp: "128/82", lastReview: "2026-07-05", nextReview: "2026-08-05", alert: "none", plan: "€39/mo" },
  { id: "p3", name: "Petras Kazlauskas", age: 71, condition: "Coronary heart disease", status: "Review due", bp: "138/88", lastReview: "2026-06-20", nextReview: "2026-07-20", alert: "review", plan: "€79/mo" },
  { id: "p4", name: "Ona Vasiliauskienė", age: 55, condition: "Hypercholesterolemia", status: "Stable", bp: "124/80", lastReview: "2026-07-01", nextReview: "2026-08-01", alert: "none", plan: "€39/mo" },
  { id: "p5", name: "Vytautas Petrauskas", age: 62, condition: "Arterial hypertension", status: "Needs attention", bp: "146/93", lastReview: "2026-06-28", nextReview: "2026-07-28", alert: "priority", plan: "€79/mo" },
  { id: "p6", name: "Danguolė Balčiūnienė", age: 49, condition: "Hypothyroidism", status: "Stable", bp: "118/76", lastReview: "2026-07-03", nextReview: "2026-08-03", alert: "none", plan: "€39/mo" },
  { id: "p7", name: "Algirdas Stankevičius", age: 67, condition: "Type 2 diabetes", status: "Review due", bp: "134/86", lastReview: "2026-06-15", nextReview: "2026-07-15", alert: "review", plan: "€79/mo" },
  { id: "p8", name: "Nijolė Jankauskienė", age: 60, condition: "Arterial hypertension", status: "Stable", bp: "126/81", lastReview: "2026-07-08", nextReview: "2026-08-08", alert: "none", plan: "€39/mo" },
  { id: "p9", name: "Bronius Vaitkus", age: 73, condition: "Coronary heart disease", status: "Needs attention", bp: "144/92", lastReview: "2026-06-22", nextReview: "2026-07-22", alert: "urgent", plan: "€79/mo" },
  { id: "p10", name: "Staselė Kazlauskienė", age: 56, condition: "Hypercholesterolemia", status: "Stable", bp: "130/83", lastReview: "2026-07-10", nextReview: "2026-08-10", alert: "none", plan: "€39/mo" },
  { id: "p11", name: "Eugenijus Petrauskas", age: 45, condition: "Preventive care", status: "Stable", bp: "120/78", lastReview: "2026-07-12", nextReview: "2026-08-12", alert: "none", plan: "€39/mo" },
  { id: "p12", name: "Irena Vasiliauskienė", age: 52, condition: "Sleep disorders", status: "Review due", bp: "132/85", lastReview: "2026-06-25", nextReview: "2026-07-25", alert: "review", plan: "€39/mo" },
  { id: "p13", name: "Gintaras Žukauskas", age: 59, condition: "Arterial hypertension", status: "Stable", bp: "128/82", lastReview: "2026-07-06", nextReview: "2026-08-06", alert: "none", plan: "€39/mo" },
  { id: "p14", name: "Aldona Petrauskienė", age: 66, condition: "Type 2 diabetes", status: "Stable", bp: "130/84", lastReview: "2026-07-02", nextReview: "2026-08-02", alert: "none", plan: "€39/mo" },
];